version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db-dts
    ports:
      - 5454:5432
    expose:
      - "5454"
    environment:
      POSTGRES_DB: CustomerArrestSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3346

  backend:
    container_name: backend-dts
    build:
      context: ..
      dockerfile: DetentionTrackingSystem/docker/builder/DockerFile
      args:
        BUILD_PATH: DetentionTrackingSystem
    ports:
      - "8090:80"
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/CustomerArrestSystem
    depends_on:
      - db


