version: '3.7'

services:
  db:
    image: postgres:latest
    ports:
      - 5455:5432
    expose:
      - 5455
    environment:
      POSTGRES_DATABASE: "$${spring.datasource.name}"
      POSTGRES_USER: "$${spring.datasource.username}"
      POSTGRES_PASSWORD: "$${spring.datasource.password}"